# Render Blueprint Configuration
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: pokernow-api
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3248
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: file:./prisma/dev.db
